NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

[DOCUMENTATION]
ORG_NAME="XLMCASH"
ORG_URL="https://xlmcash.github.io"
ORG_LOGO="https://xlmcash.github.io/images/xlmcash.png"
ORG_DESCRIPTION="**XLM Cash** represents the future of digital finance, combining the security and transparency of blockchain technology with the accessibility and convenience of modern financial services."

[[CURRENCIES]]
code="1ozSILVER"
issuer="GBQN7NQZCS4RE4S5JROWXGSHIBGEMZNM65TVBPGU5GXSSJQ2GBTYGGPP"
image="https://xlmcash.github.io/images/1ozSILVER.png"
conditions="Total Supply: 100,000,000,000"
display_decimals=7

[[CURRENCIES]]
code="ARMYXLM"
issuer="GBQN7NQZCS4RE4S5JROWXGSHIBGEMZNM65TVBPGU5GXSSJQ2GBTYGGPP"
image="https://xlmcash.github.io/images/ARMYXLM.png"
conditions="Total Supply: 100,000,000,000"
display_decimals=7

[[CURRENCIES]]
code="AUSILVER"
issuer="GBQN7NQZCS4RE4S5JROWXGSHIBGEMZNM65TVBPGU5GXSSJQ2GBTYGGPP"
image="https://xlmcash.github.io/images/AUSILVER.png"
conditions="Total Supply: 100,000,000,000"
display_decimals=7

[[CURRENCIES]]
code="EGG"
issuer="GBQN7NQZCS4RE4S5JROWXGSHIBGEMZNM65TVBPGU5GXSSJQ2GBTYGGPP"
image="https://xlmcash.github.io/images/EGG.png"
conditions="Total Supply: 100,000,000,000"
display_decimals=7

[[CURRENCIES]]
code="JOHN"
issuer="GBQN7NQZCS4RE4S5JROWXGSHIBGEMZNM65TVBPGU5GXSSJQ2GBTYGGPP"
image="https://xlmcash.github.io/images/JOHN.png"
conditions="Total Supply: 100,000,000,000"
display_decimals=7

[[CURRENCIES]]
code="RLUSD"
issuer="GBQN7NQZCS4RE4S5JROWXGSHIBGEMZNM65TVBPGU5GXSSJQ2GBTYGGPP"
image="https://xlmcash.github.io/images/RLUSD.png"
conditions="Total Supply: 100,000,000,000"
display_decimals=7

[[CURRENCIES]]
code="RUSILVER"
issuer="GBQN7NQZCS4RE4S5JROWXGSHIBGEMZNM65TVBPGU5GXSSJQ2GBTYGGPP"
image="https://xlmcash.github.io/images/RUSILVER.png"
conditions="Total Supply: 100,000,000,000"
display_decimals=7

[[CURRENCIES]]
code="USGold"
issuer="GBQN7NQZCS4RE4S5JROWXGSHIBGEMZNM65TVBPGU5GXSSJQ2GBTYGGPP"
image="https://xlmcash.github.io/images/USGold.png"
conditions="Total Supply: 100,000,000,000"
display_decimals=7

[[CURRENCIES]]
code="XAGTOK"
issuer="GBQN7NQZCS4RE4S5JROWXGSHIBGEMZNM65TVBPGU5GXSSJQ2GBTYGGPP"
image="https://xlmcash.github.io/images/XAGTOK.png"
conditions="Total Supply: 100,000,000,000"
display_decimals=7

[[CURRENCIES]]
code="XLMUSD"
issuer="GBQN7NQZCS4RE4S5JROWXGSHIBGEMZNM65TVBPGU5GXSSJQ2GBTYGGPP"
image="https://xlmcash.github.io/images/XLMUSD.png"
conditions="Total Supply: 100,000,000,000"
display_decimals=7

[[CURRENCIES]]
code="wSHX"
issuer="GBQN7NQZCS4RE4S5JROWXGSHIBGEMZNM65TVBPGU5GXSSJQ2GBTYGGPP"
image="https://xlmcash.github.io/images/wSHX.png"
conditions="Total Supply: 100,000,000,000"
display_decimals=7

[[CURRENCIES]]
code="wXXA"
issuer="GBQN7NQZCS4RE4S5JROWXGSHIBGEMZNM65TVBPGU5GXSSJQ2GBTYGGPP"
image="https://xlmcash.github.io/images/wXXA.png"
conditions="Total Supply: 100,000,000,000"
display_decimals=7

[[CURRENCIES]]
code="yXDC"
issuer="GBQN7NQZCS4RE4S5JROWXGSHIBGEMZNM65TVBPGU5GXSSJQ2GBTYGGPP"
image="https://xlmcash.github.io/images/yXDC.png"
conditions="Total Supply: 100,000,000,000"
display_decimals=7

[[CURRENCIES]]
code="yXRP"
issuer="GBQN7NQZCS4RE4S5JROWXGSHIBGEMZNM65TVBPGU5GXSSJQ2GBTYGGPP"
image="https://xlmcash.github.io/images/yXRP.png"
conditions="Total Supply: 100,000,000,000"
display_decimals=7
